### ISSUE TITLE
Publish to maven

### ISSUE THREAD

**Issue by a86c6f7964** [bivas/protobuf-java-format#1]
Start publishing the project to maven central repo.

**Comment by scr** [comment]
@bivas - Any chance there can be a push to maven any time soon?  I'd like to use the latest JsonJackonFormatter and it's not available on the latest 1.2 version

http://search.maven.org/#artifactdetails%7Ccom.googlecode.protobuf-java-format%7Cprotobuf-java-format%7C1.2%7Cjar

**Comment by scr** [comment]
I guess, I'd like to see 1.3 released, most importantly, but, short of that, is the 1.3-SNAPSHOT available from any repo?

**Comment by bivas** [comment]
I haven't released anything for real long time. If you like, you're welcome
to add yourself to the commiters sections and release a new version.

Eliran Bivas

**Comment by scr** [comment]
Thanks - is there a write up of your deployment mechanism?  I personally deploy to sonatype using their plugin for https://github.com/scr/j8iterables - I'll try the usual directives and see where I get stuck.

**Comment by scr** [comment]
I'm not sure I understand what you meant when you said "add yourself to the commiters sections" - Does https://github.com/bivas/protobuf-java-format/pull/8 solve it (By adding to the developers in the pom.xml?).

Here's what I see when I run

`mvn clean deploy -DsignArtifacts=true`:

* With `nexus-staging-maven-plugin` for deployment: https://gist.github.com/scr/a0a73013759bc38808d8
* With `maven-deploy-plugin` for deployment: https://gist.github.com/scr/fbb2b23a1d74be4447e9

**Comment by bivas** [comment]
@scr yes, issue #8 solve it

**Comment by scr** [comment]
Hmm… @bivas - I'm wondering - did the `<id>...</id>` need to be my sonatype id? I just followed the convention you had of firstname.lastname, thinking it was just a maven-specific ID of sorts.

Please merge PR #9 to see if that helps.

**Comment by bivas** [comment]
@scr I've merged it. Do you need my access token for Sonatype release?
Can you post here the errors you're getting when you attempt a release?

**Comment by scr** [comment]
```
[INFO] Deploying remotely...
[INFO] Bulk deploying locally gathered artifacts from directory: 
[INFO]  * Bulk deploying locally gathered snapshot artifacts to URL https://oss.sonatype.org/content/repositories/snapshots
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/protobuf-java-format/protobuf-java-format/1.4-SNAPSHOT/maven-metadata.xml
Uploading: https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/protobuf-java-format/protobuf-java-format/1.4-SNAPSHOT/protobuf-java-format-1.4-20151018.185229-1.jar
Uploading: https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/protobuf-java-format/protobuf-java-format/1.4-SNAPSHOT/protobuf-java-format-1.4-20151018.185229-1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.673 s
[INFO] Finished at: 2015-10-18T11:52:31-07:00
[INFO] Final Memory: 35M/145M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:deploy (injected-nexus-deploy) on project protobuf-java-format: Failed to deploy artifacts: Could not transfer artifact com.googlecode.protobuf-java-format:protobuf-java-format:jar:1.4-20151018.185229-1 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Access denied to: https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/protobuf-java-format/protobuf-java-format/1.4-SNAPSHOT/protobuf-java-format-1.4-20151018.185229-1.jar, ReasonPhrase: Forbidden. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by scr** [comment]
FYI, I tried with -DsignArtifacts but the results didn't change.

**Comment by bivas** [comment]
You don't have access to that repo as I'm the owner. Have you set anything
in settings.xml?

*Eliran Bivas*

--

**Comment by scr** [comment]
@bivas - I filed https://issues.sonatype.org/browse/OSSRH-18347 to ask Sonatype to help us with extending permissions to deploy.

**Comment by bivas** [comment]
@scr Got my approval (and blessing).

**Comment by bivas** [comment]
@scr SonaType added your id to publishers. Lets give it another run.

**Comment by scr** [comment]
It looks like 1.3 went through!!!  Please pull #10 and do:

```
git tag 1.3 23b27d51be2564b517a311fa5fe4a6652497cb7e
```

**Comment by bivas** [comment]
Done
