### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by ebourg** [bivas/protobuf-java-format#29]
Hi,

The GitHub repository is missing some release tags for the old releases, could you please consider adding them? Here are the commits matching the release dates on https://code.google.com/archive/p/protobuf-java-format/downloads

    git tag 1.2   8d4e755fca74820578885909f93ce50c14fc3889
    git tag 1.1.1 dabc9ef2f74e67e30a0596874a24f51248580ad0
    git tag 1.1   660fcd81a67c48b2ea160e0aee3e5fa853c248ae
    git tag 1.0   daeb86721223a1f12be6b6026aa1c7444f4d0603
    git push --tags

Thank you

**Comment by scr** [comment]
Done

**Comment by ebourg** [comment]
Thank you!
