### ISSUE TITLE
Add some documentation to contribute to the project

### ISSUE THREAD

**Issue by whiver** [bivas/protobuf-java-format#45]
It would be find if we had more documentation about how to contribute to the project, cause I cannot manage to build the source code to solve issue #44.

I installed `protoc` and ran `mvn test` but I get errors about packages not found like that:

```
[ERROR] /home/wsh/Documents/protobuf-java-format/target/generated-test-sources/protobuf_unittest/UnittestProto.java:[13217,44] error: package com.google.protobuf.GeneratedMessageV3 does not exist
```

I suppose there is some more steps to generate these files but I don't know which...

**Comment by whiver** [comment]
Okay I finally got it work by updating the Protobuf dependency to v3.5.0.

**Comment by bivas** [comment]
Would you like to create such doc? A pull request is welcome

**Comment by whiver** [comment]
Yep, I'll see that.
